### ISSUE TITLE
Change needle style

### ISSUE THREAD

**Issue by mehrdad-shokri** [Sulejman/GaugeView#6]
@Sulejman thanks for your repository.  
Im trying to achieve something like
![this](https://cloud.githubusercontent.com/assets/13661520/18522018/961f9b6a-7ac3-11e6-9b07-123479a798ca.jpg) for needle effect.  
Seems like I can't make it appear like that.  
can provide a snippet for that?

**Comment by Sulejman** [comment]
I am currently busy so I don't believe I will have time for this soon. However, if I would do it, it would be freelancer work (paid). Maybe in future I will do it anyway but I don't know will it be fast enough for your project.

**Comment by mehrdad-shokri** [comment]
I didn't ask for the whole project, my question was how to draw that small blue indicator.

**Comment by mehrdad-shokri** [comment]
I solved it thanks.
![photo_2016-09-15_15-17-03](https://cloud.githubusercontent.com/assets/13661520/18547290/dd962790-7b57-11e6-83ec-d1ad4e5c6ed4.jpg)
